server:
  port: 8020
spring:
  application:
    name: pay
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Haso-soft.com88
    url: jdbc:mysql://192.168.1.38:3306/pay
